// ---------- DATA: land border pairs ----------
const EDGES = [
// Europe
["Portugal","Spain"],["Spain","France"],["Spain","Andorra"],["Spain","Morocco"],
["France","Andorra"],["France","Monaco"],["France","Belgium"],["France","Luxembourg"],["France","Germany"],["France","Switzerland"],["France","Italy"],
["Belgium","Netherlands"],["Belgium","Luxembourg"],["Belgium","Germany"],["Netherlands","Germany"],
["Germany","Luxembourg"],["Germany","Switzerland"],["Germany","Austria"],["Germany","Czechia"],["Germany","Poland"],["Germany","Denmark"],
["Switzerland","Italy"],["Switzerland","Austria"],["Switzerland","Liechtenstein"],
["Austria","Liechtenstein"],["Austria","Italy"],["Austria","Slovenia"],["Austria","Hungary"],["Austria","Slovakia"],["Austria","Czechia"],
["Italy","Slovenia"],["Italy","San Marino"],["Italy","Vatican City"],
["Slovenia","Croatia"],["Slovenia","Hungary"],
["Croatia","Hungary"],["Croatia","Serbia"],["Croatia","Bosnia and Herzegovina"],["Croatia","Montenegro"],
["Bosnia and Herzegovina","Serbia"],["Bosnia and Herzegovina","Montenegro"],
["Serbia","Montenegro"],["Serbia","Hungary"],["Serbia","Romania"],["Serbia","Bulgaria"],["Serbia","North Macedonia"],["Serbia","Kosovo"],
["Kosovo","Montenegro"],["Kosovo","Albania"],["Kosovo","North Macedonia"],
["Montenegro","Albania"],["Albania","North Macedonia"],["Albania","Greece"],
["North Macedonia","Greece"],["North Macedonia","Bulgaria"],
["Greece","Bulgaria"],["Greece","Turkey"],
["Bulgaria","Romania"],["Bulgaria","Turkey"],
["Romania","Hungary"],["Romania","Ukraine"],["Romania","Moldova"],["Moldova","Ukraine"],
["Hungary","Slovakia"],["Hungary","Ukraine"],
["Slovakia","Czechia"],["Slovakia","Poland"],["Slovakia","Ukraine"],
["Poland","Czechia"],["Poland","Ukraine"],["Poland","Belarus"],["Poland","Lithuania"],["Poland","Russia"],
["Lithuania","Belarus"],["Lithuania","Latvia"],["Lithuania","Russia"],
["Latvia","Belarus"],["Latvia","Estonia"],["Latvia","Russia"],
["Estonia","Russia"],["Belarus","Ukraine"],["Belarus","Russia"],["Ukraine","Russia"],
["Finland","Russia"],["Finland","Sweden"],["Finland","Norway"],["Sweden","Norway"],["Norway","Russia"],
["Ireland","United Kingdom"],
// Caucasus & Middle East
["Turkey","Georgia"],["Turkey","Armenia"],["Turkey","Azerbaijan"],["Turkey","Iran"],["Turkey","Iraq"],["Turkey","Syria"],
["Georgia","Russia"],["Georgia","Armenia"],["Georgia","Azerbaijan"],
["Armenia","Azerbaijan"],["Armenia","Iran"],["Azerbaijan","Russia"],["Azerbaijan","Iran"],
["Syria","Iraq"],["Syria","Jordan"],["Syria","Lebanon"],["Syria","Israel"],
["Israel","Lebanon"],["Israel","Jordan"],["Israel","Egypt"],["Israel","Palestine"],
["Palestine","Jordan"],["Palestine","Egypt"],
["Jordan","Iraq"],["Jordan","Saudi Arabia"],
["Iraq","Iran"],["Iraq","Saudi Arabia"],["Iraq","Kuwait"],
["Saudi Arabia","Kuwait"],["Saudi Arabia","Qatar"],["Saudi Arabia","United Arab Emirates"],["Saudi Arabia","Oman"],["Saudi Arabia","Yemen"],
["United Arab Emirates","Oman"],["Oman","Yemen"],
// Central & South Asia
["Russia","Kazakhstan"],["Russia","Mongolia"],["Russia","China"],["Russia","North Korea"],
["Kazakhstan","China"],["Kazakhstan","Kyrgyzstan"],["Kazakhstan","Uzbekistan"],["Kazakhstan","Turkmenistan"],
["Kyrgyzstan","China"],["Kyrgyzstan","Tajikistan"],["Kyrgyzstan","Uzbekistan"],
["Tajikistan","China"],["Tajikistan","Afghanistan"],["Tajikistan","Uzbekistan"],
["Uzbekistan","Afghanistan"],["Uzbekistan","Turkmenistan"],
["Turkmenistan","Afghanistan"],["Turkmenistan","Iran"],
["Afghanistan","Iran"],["Afghanistan","Pakistan"],["Afghanistan","China"],
["Iran","Pakistan"],["Pakistan","India"],["Pakistan","China"],
["India","China"],["India","Nepal"],["India","Bhutan"],["India","Bangladesh"],["India","Myanmar"],
["Nepal","China"],["Bhutan","China"],
["China","Mongolia"],["China","North Korea"],["China","Myanmar"],["China","Laos"],["China","Vietnam"],
["North Korea","South Korea"],
// Southeast Asia
["Myanmar","Bangladesh"],["Myanmar","Laos"],["Myanmar","Thailand"],
["Laos","Thailand"],["Laos","Vietnam"],["Laos","Cambodia"],
["Thailand","Cambodia"],["Thailand","Malaysia"],
["Cambodia","Vietnam"],
["Malaysia","Indonesia"],["Malaysia","Brunei"],
["Indonesia","Papua New Guinea"],["Indonesia","Timor-Leste"],
// Africa
["Egypt","Libya"],["Egypt","Sudan"],
["Libya","Tunisia"],["Libya","Algeria"],["Libya","Niger"],["Libya","Chad"],["Libya","Sudan"],
["Tunisia","Algeria"],
["Algeria","Morocco"],["Algeria","Mauritania"],["Algeria","Mali"],["Algeria","Niger"],
["Mauritania","Mali"],["Mauritania","Senegal"],
["Senegal","Mali"],["Senegal","Guinea"],["Senegal","Guinea-Bissau"],["Senegal","Gambia"],
["Guinea-Bissau","Guinea"],
["Guinea","Mali"],["Guinea","Sierra Leone"],["Guinea","Liberia"],["Guinea","Ivory Coast"],
["Sierra Leone","Liberia"],["Liberia","Ivory Coast"],
["Ivory Coast","Mali"],["Ivory Coast","Burkina Faso"],["Ivory Coast","Ghana"],
["Mali","Burkina Faso"],["Mali","Niger"],
["Burkina Faso","Ghana"],["Burkina Faso","Togo"],["Burkina Faso","Benin"],["Burkina Faso","Niger"],
["Ghana","Togo"],["Togo","Benin"],
["Benin","Niger"],["Benin","Nigeria"],
["Niger","Nigeria"],["Niger","Chad"],
["Nigeria","Chad"],["Nigeria","Cameroon"],
["Chad","Cameroon"],["Chad","Central African Republic"],["Chad","Sudan"],
["Cameroon","Central African Republic"],["Cameroon","Equatorial Guinea"],["Cameroon","Gabon"],["Cameroon","Congo"],
["Equatorial Guinea","Gabon"],["Gabon","Congo"],
["Congo","DR Congo"],["Congo","Central African Republic"],["Congo","Angola"],
["Central African Republic","Sudan"],["Central African Republic","South Sudan"],["Central African Republic","DR Congo"],
["Sudan","South Sudan"],["Sudan","Eritrea"],["Sudan","Ethiopia"],
["South Sudan","Ethiopia"],["South Sudan","Kenya"],["South Sudan","Uganda"],["South Sudan","DR Congo"],
["Eritrea","Ethiopia"],["Eritrea","Djibouti"],
["Ethiopia","Djibouti"],["Ethiopia","Somalia"],["Ethiopia","Kenya"],
["Djibouti","Somalia"],["Somalia","Kenya"],
["Kenya","Uganda"],["Kenya","Tanzania"],
["Uganda","DR Congo"],["Uganda","Rwanda"],["Uganda","Tanzania"],
["Rwanda","DR Congo"],["Rwanda","Burundi"],["Rwanda","Tanzania"],
["Burundi","DR Congo"],["Burundi","Tanzania"],
["Tanzania","DR Congo"],["Tanzania","Zambia"],["Tanzania","Malawi"],["Tanzania","Mozambique"],
["DR Congo","Zambia"],["DR Congo","Angola"],
["Angola","Zambia"],["Angola","Namibia"],
["Zambia","Malawi"],["Zambia","Mozambique"],["Zambia","Zimbabwe"],["Zambia","Botswana"],["Zambia","Namibia"],
["Malawi","Mozambique"],
["Mozambique","Zimbabwe"],["Mozambique","South Africa"],["Mozambique","Eswatini"],
["Zimbabwe","Botswana"],["Zimbabwe","South Africa"],
["Botswana","Namibia"],["Botswana","South Africa"],
["Namibia","South Africa"],
["South Africa","Eswatini"],["South Africa","Lesotho"],
// Americas
["Canada","United States"],["United States","Mexico"],
["Mexico","Guatemala"],["Mexico","Belize"],
["Guatemala","Belize"],["Guatemala","Honduras"],["Guatemala","El Salvador"],
["El Salvador","Honduras"],["Honduras","Nicaragua"],["Nicaragua","Costa Rica"],["Costa Rica","Panama"],
["Panama","Colombia"],
["Colombia","Venezuela"],["Colombia","Ecuador"],["Colombia","Peru"],["Colombia","Brazil"],
["Venezuela","Brazil"],["Venezuela","Guyana"],
["Guyana","Brazil"],["Guyana","Suriname"],["Suriname","Brazil"],
["Ecuador","Peru"],
["Peru","Brazil"],["Peru","Bolivia"],["Peru","Chile"],
["Bolivia","Brazil"],["Bolivia","Paraguay"],["Bolivia","Chile"],["Bolivia","Argentina"],
["Paraguay","Brazil"],["Paraguay","Argentina"],
["Brazil","Argentina"],["Brazil","Uruguay"],
["Argentina","Chile"],["Argentina","Uruguay"],
["Haiti","Dominican Republic"],
];

// ---------- DATA: fixed daily-puzzle launch date ----------
const LAUNCH = Date.UTC(2026,6,1); // Jul 1 2026
